dependencies {
    implementation libs.boot.starter.webflux
    implementation platform('software.amazon.awssdk:bom:2.27.21')
    implementation "software.amazon.awssdk:lambda"
    compileOnly 'org.projectlombok:lombok:1.18.32'
    annotationProcessor 'org.projectlombok:lombok:1.18.32'
    implementation 'org.mapstruct:mapstruct:1.5.5.Final'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.5.5.Final'
}